### ISSUE TITLE
using smartLife account

### ISSUE THREAD

**Issue by wouldsmina** [mrdvt92/perl-WebService-Tuya-IoT-API#1]
Hello,

I am using SmartLife application. When I tested your Perl library, I encountered an error indicating a non-existent account. Is the API for SmartLife different from that of Tuya? If so, do you know how to work around this issue without having to create a Tuya account? 

Thanks

**Comment by wouldsmina** [comment]
I finally created an account on iot.tuya.com. The interface offers different types of projects (product, app, cloud, etc.). What type of project should I create to use your library?

**Comment by wouldsmina** [comment]
I think I've found it. I need to create a cloud project, then go to the 'devices' tab to associate the Smart Life app with the QR code. I'll continue to experiment until I succeed. Thanks for your work on this project anyway.

**Comment by mrdvt92** [comment]
> I need to create a cloud project, then go to the 'devices' tab to associate the Smart Life app with the QR code.

If you would, please review the [setup documentation](https://metacpan.org/pod/WebService::Tuya::IoT::API#SETUP) and let me know how it did not meet your needs.  I would appreciate your review.
